#!/bin/sh

dir=`pwd`

imagesets=`find $dir -name '*.imageset'`
count=`find $dir -name '*.imageset' | wc -l`
i=0
while read imgset
do
 images=`find $imgset -name '*.png'`
 curl
 exit
 i=$[$i+1]
 sch=$[$i*100/count]
 s=$(printf %-"$[$sch/2]"s "#")
 #printf "进度:[%-50s]%d%%\r" "${s// /#}" $sch
done <<EOF
$imagesets
EOF

