#!/bin/sh

writeExportPlist(){
(
cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>compileBitcode</key>
    <true/>
    <key>method</key>
    <string>$2</string>
</dict>
</plist>
EOF
) > $1
}

home='/Users/clearlove'
base=`pwd`
projectName=`ls | grep xcodeproj`
AppName=${projectName%.*}
exportOptionsPlistPath='./build/exportOptions.plist'


if [ -z "$AppName" ]; then
 exit
fi

rm -rf build

pod install

xcodebuild -workspace $AppName.xcworkspace -scheme $AppName archive -archivePath build/target.dev.xcarchive -sdk iphoneos10.2 -configuration Debug CONFIGUTATION_BUILD_DIR='build'
writeExportPlist $exportOptionsPlistPath ad-hoc
xcodebuild -exportArchive -archivePath ./build/target.dev.xcarchive/ -exportPath ./build/dev -exportOptionsPlist "$exportOptionsPlistPath"
rm $exportOptionsPlistPath

version=`defaults read $base/$AppName/Info.plist CFBundleShortVersionString`

echo '开始上传debug包'
sshpass -p 'root' scp -P32770 ./build/dev/$AppName.ipa root@192.168.2.247:~/$AppName.ipa

getopts "r" opt
if [ $opt = "?" ] ; then
 echo 'debug包部署完成'
 exit
fi
 
xcodebuild -workspace $AppName.xcworkspace -scheme $AppName archive -archivePath build/target.pro.xcarchive -sdk iphoneos10.2 -configuration Release CONFIGUTATION_BUILD_DIR='build'
writeExportPlist $exportOptionsPlistPath ad-hoc
xcodebuild -exportArchive -archivePath ./build/target.pro.xcarchive/ -exportPath ./build/pro -exportOptionsPlist "$exportOptionsPlistPath"
rm $exportOptionsPlistPath

echo '开始上传pro包'
sshpass -p 'root' scp -P32770 ./build/pro/$AppName.ipa root@192.168.2.247:~/output/$AppName.$version.pro.ipa
echo '执行pro包发部脚本'
sshpass -p 'root' ssh -t -p32770 root@192.168.2.247 "./deploy.sh"

echo '开始上传dev包'
sshpass -p 'root' scp -P32770 ./build/dev/$AppName.ipa root@192.168.2.247:~/output/$AppName.$version.dev.ipa
echo '执行dev包发部脚本'
sshpass -p 'root' ssh -t -p32770 root@192.168.2.247 "./deploy.sh"

echo '生成manifest中'

evs=("pro" "dev")
for e in ${evs[*]}
do
 manifestPath="$home/Developer/fuckApp/manifest.$version.$e.plist"
 cp ~/Developer/fuckApp/manifest.plist $manifestPath
 sed -i '' "s/>[0-9]\.[0-9]\.[0-9]/>$version/" $manifestPath
 sed -i '' "s/$AppName.ipa/output\/$AppName.$version.$e.ipa/" $manifestPath
done

cd ~/Developer/fuckApp

git add *
git commit -am "release $version manifest"
git push

echo '打包完成'

