#!/bin/sh

base=`pwd`

# xcodebuild -workspace $AppName.xcworkspace -scheme "$AppName"X archive -archivePath build/target.dev.xcarchive -sdk iphoneos10.2 -configuration Release CONFIGUTATION_BUILD_DIR='build'
# xcodebuild -exportArchive -exportFormat IPA -archivePath build/target.pro.xcarchive/ -exportPath ./build/$AppName.dev.ipa -exportProvisioningProfile $AdHocProvisioningProfile

version=`defaults read $base/$AppName/Info.plist CFBundleShortVersionString`

echo '开始上传debug包'
scp -P32770 ./build/$AppName.dev.ipa root@192.168.2.247:~/$AppName.ipa

getopts "r" opt
if [ $opt = "?" ] ; then
 exit
fi
 
# xcodebuild -workspace $AppName.xcworkspace -scheme $AppName archive -archivePath build/target.pro.xcarchive -sdk iphoneos10.2 -configuration Release CONFIGUTATION_BUILD_DIR='build'
# xcodebuild -exportArchive -exportFormat IPA -archivePath build/target.pro.xcarchive/ -exportPath ./build/$AppName.pro.ipa -exportProvisioningProfile $AdHocProvisioningProfile

echo '开始上传pro包'
scp -P32770 ./build/$AppName.pro.ipa root@192.168.2.247:~/output/$AppName.$version.pro.ipa
ssh -t -p32770 root@192.168.2.247 "./deploy.sh"

echo '开始上传dev包'
scp -P32770 ./build/$AppName.dev.ipa root@192.168.2.247:~/output/$AppName.$version.dev.ipa
ssh -t -p32770 root@192.168.2.247 "./deploy.sh"

echo '生成manifest中'

evs=("pro" "dev")
for e in ${evs[*]}
do
 manifestPath="~Developer/fuckApp/manifest.$version.$e.plist"
 cp ~/Developer/fuckApp/manifest.plist $manifestPath
 sed -i "s/>[0-9]\.[0-9]\.[0-9]/>$version/" $manifestPath
 sed -i "s/$AppName.ipa/output\/$AppName.$version.$e.ipa/" $manifestPath
done

cd ~/Developer/fuckApp

git add *
git commit -am "release $version manifest"
git push

echo '打包完成'
